module.exports={
    configureWebpack:{
        //给文件配置别名
        resolve:{
            alias:{
                'assets':'@/assets',
                'common':'@/common',
                'components':'@/components',
                'network':'@network',
                'views':'@views'
            }
        }
    }
}